name: QraphQL schema publish
 
on: 
  push:
    branches:
      - main
 
jobs:
  test:
    name: Publish schema
    runs-on: ubuntu-latest
    environment: production
    env: 
      HIVE_TOKEN: ${{ secrets.HIVE_TOKEN }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install GraphQL Hive CLI
        run: |
          curl -sSL https://graphql-hive.com/install.sh | sh
 
      - name: Schema Publish
        run: hive schema:publish ./schema.gql --github