name: QraphQL schema publish
 
on: 
  pull_request:
    branches:
      - main
    types:
      - closed
 
jobs:
  test:
    if: ${{ github.event.pull_request.merged }}
    name: Check Schema
    runs-on: ubuntu-latest
    environment: production
    env: 
      HIVE_TOKEN: ${{ secrets.HIVE_TOKEN }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install GraphQL Hive CLI
        run: |
          curl -sSL https://graphql-hive.com/install.sh | sh
 
      - name: Schema Check
        run: hive schema:publish ./schema.gql --github